---
title: Pets on Wheels of Scottsdale, Inc
author: Pets on Wheels of Scottsdale, Inc
email: contact@petsonwheelsscottsdale.org
description: The purpose of Pets on Wheels is to enhance the lives of the elderly
  and/or infirm, now relegated to routine and often uncomfortable lives in special
  care centers, such as nursing homes and hospitals. Other purposes are to assist
  in the rehabilitation of special injury or post-surgical patients and to help build
  self-esteem in young students in special classes, as well as to divert the attention
  of cancer patients from their worries.
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
